# IDRiD CIR Composition Task
# Data nums: ~2000 (IDRiD dataset)

includes:
- idrid_dataset_cfg.yaml

model_config:
  fashionclip:
    training_head_type: mtl
    clip_config:
      clip_model_name: /data0/qrchen/projects/FAME-ViL/pretrained_models/clip-vit-base-patch16
    adapter_config:
      freeze: false
      adapter_name: scaled_pa
      bottleneck: 64
      dropout: 0.0
      enable_xattn: true
      share_cross: false
      share_adapter: false
      cross_dropout: 0.0
    lr_multiplier: 100
    tasks:
    - tgir

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 1200
    - 2400
    - 4000
    lr_ratio: 0.1
    warmup_iterations: 200
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-6
    eps: 1e-8
    weight_decay: 1e-5

evaluation:
  metrics:
    - r@k_idrid

training:
  experiment_name: fashionclip_idrid_composition_xattn
  batch_size: 32
  lr_scheduler: true
  max_updates: 6000
  log_interval: 10
  checkpoint_interval: 5620
  evaluation_interval: 562
  find_unused_parameters: true
  early_stop:
    criteria: idrid/r@k_idrid/Avg_Recall
    minimize: false
  wandb:
    enabled: false

run_type: train_val
